rdeits/meshcat-python

Readme.rst, demo.ipynb, src/meshcat/commands.py, src/meshcat/servers/tree.py, src/meshcat/servers/zmqserver.py, src/meshcat/tests/test_drawing.py, src/meshcat/visualizer.py
Fixes #5 
This means that opening a new window pointing to the same server will result in the same 3D scene being displayed, so it should not be necessary to pre-emptively or periodically re-transmit all the set_object commands. In addition, it should be safe to refresh the browser view at any time.
=> zmq server remembers the entire scene tree and replays it to new websockets

src/meshcat/geometry.py
This is sanity-checkable by attempting to publish a point cloud with some known structure -- e.g. a point cloud that should be a random set of points on the ground. Not sure how to test for that in a unit-test sort of framework, though.
Enables pretty viz (though I'm still fixing up some camera intrinsic stuff).
=> Force tobytes() to use appropriate ordering

src/meshcat/geometry.py
Fix https://github.com/rdeits/meshcat-python/issues/35
Add support for transparent material, using Three.js transparent and opacity attributes (see https://threejs.org/docs/#api/en/materials/Material.opacity).
=> Add support for transparent mesh material.

src/meshcat/examples/lines.ipynb, src/meshcat/geometry.py
The changes were trivial in the end. I just added the following,
```python
class Line(Object):
_type = u"Line"
class LineSegments(Object):
_type = u"LineSegments"
class LineLoop(Object):
_type = u"LineLoop"
```
I spend most of the time testing the different rending options (Line, LineSegement and LineLoop) in the included [lines.ipynb](https://github.com/danieljfarrell/meshcat-python/blob/master/src/meshcat/examples/lines.ipynb). In this notebook I also played around a little with using materials to give the lines different colours. It seems they can be rendered using standard mesh materials. 
I also thought about adding https://threejs.org/docs/#api/en/materials/LineBasicMaterial and https://threejs.org/docs/#api/en/materials/LineDashMaterial but decided against it so as to keep this …
=> Added basic support of Line, LineSegment and LineLoop

src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
If mesh already exists in memory it is inefficient to save the mesh to a file and reload it. This can be avoided using streams.
```python
f = io.StringIO('mesh ascii')  # or io.BytesIO('mesh binary')
```
The `from_file` methods open the file and then load,
```python
@staticmethod
def from_file(fname):
with open(fname, "r") as f:
return MeshGeometry(f.read(), u"dae")
```
The `from_steam` methods skip the `with open` step and load the data in the stream directly.
```python
@staticmethod
def from_stream(f):
return MeshGeometry(data_from_stream(f), u"dae")
```
`StringIO` changes quite a bit between Python 2 and Python 3 and I noticed you are supporting Python 2 so I made it work in both cases. `data_from_stream` looks like this,
```python
def data_from_stream(stream):
if sys.version_info >= …
```
=> Added `from_stream` method to MeshGeometry subclasses.

Readme.rst
To install `libzmq3` in apt you need to do `sudo apt-get install libzmq3-dev` because the package `libzmq3` does not exist.
Tested and installed on Ubuntu 16.04.
=> fix zmq installation apt package

src/meshcat/servers/zmqserver.py, src/meshcat/tests/test_drawing.py, src/meshcat/visualizer.py
Adds the capability to generate a standalone static HTML page from the visualizer object.
Usage:
```
vis = Visualizer()
res = vis.statc_html()
with open("test.html", "w") as f:
f.write(res)
```
At this point you have a `test.html` file that standalone has your entire Meshcat scene in it.
=> Save scene into static JSON

src/meshcat/servers/zmqserver.py, src/meshcat/visualizer.py
- Adds `args` argument to the initializer of `ViewerWindow`. These `args` will be passed onto the `ZMQWebSocketBridge`. `Visualizer` passes its command line arguments onto the `ViewerWindow`.
- Adds keyboard interrupt handling for the `Visualizer`.
Reverted the below:
> - Upstreams the viewer. Now supporting loading meshes with textures.
> - Adds file handler to the `ZMQWebSocketBridge`
>     - Only known file types are served: stl, obj, dae, png, bmp, jpeg, jpg, mtl
>     - Adds `--file-root` `-f`argument. This path is the relative path for searching for files. It can be set to `/` (`-f=/`) to allow access to the whole file system (useful when exposing ROS packages).
>     - Exposes a file serving URL `http://[your_url]/files/`. Http request to this URL will strip this string and prepend …
=> Expose/serve local files via the ZMQWebSocketBridge

src/meshcat/visualizer.py
I've got meshcat working on colab ([simple version](https://colab.research.google.com/drive/1O-WgLtqKGuHKEeD4CFT69870dPEJRsQJ), [manipulation teleop demo](https://colab.research.google.com/drive/1PvEXUdmwL_W9yzncyJR7fOHYDLUXj-P2)) now, which makes me very happy.  But I had to do a bunch of little hacks to get things to work.  I'll upstream the ones that I think make sense.
This is the first one.  WDYT?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rdeits/meshcat-python/65)
=> pass PYTHONPATH to Popen

.travis.yml, setup.py, src/meshcat/servers/zmqserver.py, src/meshcat/tests/test_start_server.py, src/meshcat/visualizer.py
pulls it out of Visualizer class so that it can used to start a stand-alone server from python / jupyter
adds support for ngrok http tunnels, which allows one to make a public url from a machine that does not have a public hostname.
did a little dance to make sure it still works with python2.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rdeits/meshcat-python/68)
=> Generalizes "start_server" logic

src/meshcat/servers/zmqserver.py
It was triggering deprecation warnings on ubuntu focal:
"Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working".
and, it turns out, was not actually being used.
=> Remove unused import from collections.

src/meshcat/servers/zmqserver.py
If the `zmqserver` gets a `set_object` command that sets precisely the same object data on precisely the same path that already exists, then do not forward it to the connected websockets.
This makes a *dramatic* improvement in the workflow of using meshcat on colab (at least as we use it in drake), because we don't have to repeatedly download large meshfiles from repeated simulations.
=> zmqserver can cache objects

setup.py, src/meshcat/servers/zmqserver.py
Related to https://github.com/RussTedrake/manipulation/issues/93
pyngrok 5.0.0 change the return type of the connect method. I've added logic to handle both versions. I've also made the output from the zmq server more robust when the subprocess fails (it was currently silent).
since we don't test pyngrok locally and I want to show you multiple versions, i've put a test case here: https://colab.research.google.com/drive/1N7X9keUQJwPWSrcX01rOfkNW6v_N9Lyv#scrollTo=KIKt347N_g0n
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rdeits/meshcat-python/80)
=> support pyngrok 5

src/meshcat/servers/zmqserver.py
=> Pass the full environment to the subprocess rather than just PYTHONPATH

src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
I've been using this quite successfully in the course repos using a local modification.  
https://github.com/RussTedrake/underactuated/blob/master/underactuated/meshcat_utils.py#L12
Finally pushing it back upstream.
=> Add support for vertex coloring in TriangularMeshGeometry

.gitignore, setup.py, src/meshcat/commands.py, src/meshcat/servers/zmqserver.py, src/meshcat/visualizer.py
This PR follows https://github.com/rdeits/meshcat/pull/85.
It adds a new `get_image()` method to `meshcat.Visualizer`. This relies on the new `capture_image` command added in rdeits/meshcat#85 which queries an image returned to the Meshcat client as a PNG in base64 data URI form.
On the Python side, the WebsocketHandler awaits the response from the Meshcat client, and when it receives the JSON from the frontend, the `on_message()` callback is triggered, which sends the PNG (turned into a sequence of bytes) over the ZMQ bridge.
The design is not completely robust yet. It requires the browser window be already open to get a response in the client (the visualizer will block until then).  
Maybe this behavior can be fixed by using something else to get the PNG render.
=> New feature: capture image

src/meshcat/visualizer.py
This PR allows the user to specify the height of the rendered HTML div when calling `jupyter_cell()`, which is good for people on HiDPI screens who don't use UI scaling
=> (visualizer) specify height in jupyter_cell

src/meshcat/animation.py
The issue: The `output.mp4` saved by `convert_frames_to_video` isn't playable by QuickTime player on Mac (@TobiaMarcucci had issues playing it with many other apps on Mac too).
The fix: Based on https://apple.stackexchange.com/questions/166553/why-wont-video-from-ffmpeg-show-in-quicktime-imovie-or-quick-preview, pixel format incompatibility is the culprit, hence the simple fix. (apparently @DannyDriess had suggested this very fix in our discussion thread and I missed it; sorry Danny.)
Also, https://stackoverflow.com/questions/46164041/default-pixel-format-for-ffmpeg-for-encoding-an-image-stack-to-movie suggests that `ffmpeg` isn't particularly picky about the `-pix_fmt` flag as its default behavior is on a case-by-case basis and platform-agnostic anyway. So I felt comfortable enough …
=> Fix mp4 unplayable on Mac

examples/demo.ipynb, src/meshcat/commands.py, src/meshcat/geometry.py
I do not claim any credit for this work, I merely squashed & rebased @shensquared's work in https://github.com/rdeits/meshcat-python/pull/32. The only "intelligent" change I had to do is remove a use of `unicode` since we're python3 now.
I tested the relevant `demo.ipynb` and was able to reproduce the results. Here's the state after the final cell is run:
I hope this will save you some work, and help merge this nice feature to `meshcat` :)
=> [rebased] Text rendering: python-side 

.github/workflows/CI.yaml
Python 3.6 is not available in ubuntu-latest (22.04).
This PR merely changes ``(ubuntu-latest, python-3.6)`` to ``(ubuntu-20.04, python-3.6)`` in the matrix strategy.
=> Fix continuous integration matrix

.github/workflows/CI.yaml
As of February 1, 2022, v1 [has been fully sunset](https://github.com/codecov/codecov-action#readme) and no longer functions. This is likely the cause of the [error we see in windows-latest jobs](https://github.com/rdeits/meshcat-python/actions/runs/3983333631/jobs/6828572853):
{'detail': ErrorDetail(string='Missing "owner" argument. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
This PR updates to Codecov v3.
=> CI: update Codecov to v3
