rdeits/meshcat-python

.gitignore, src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/servers/zmqserver.py, src/meshcat/tests/test_ports.py
=> Fix python 2.7 compatibility

src/meshcat/servers/zmqserver.py, src/meshcat/visualizer.py
=> more careful printing and checking of zmq and web urls

.gitignore, MANIFEST.in, src/meshcat/animation.py
cc @TobiaMarcucci
Fixes #20 
Fixes #19
=> fix some missing unicode in python2 for animations

src/meshcat/visualizer.py
ViewerWindow.__del__ was not getting called reliably (actually not ever in my uses) on exit.  As a result, the subprocesses were getting left open (consuming the port).
Everything that I just read about subprocess management, etc, says not to hope for GC to do the work.  Most posts think it's better to register the cleanup using atexit().  They also say it's important to not register the cleanup as a system method, which would artificially extend the lifetime of that object.
I've implemented what I perceive to be the recommended version, for your consideration.  This obviously defers the cleanup until the program ends (instead of the object's lifetime ending), but it's more robust.
=> close viewer subprocess with atexit()

.travis.yml, src/meshcat/transformations.py
=> fix incorrect escape sequences in the transformations library

demo.ipynb, src/meshcat/geometry.py
Goes along with https://github.com/rdeits/meshcat/pull/48
TODO:
=> Add DaeMeshGeometry, StlMeshGeometry and abstract class MeshGeometry

src/meshcat/servers/zmqserver.py
Resolves #55 
I do not have a min reproduction, but can try to do so if it's important.
=> zmqserver: Do not cache local files

src/meshcat/servers/zmqserver.py
=> ioloop.install() no longer necessary for pyzmq >= 17

.gitignore, src/meshcat/servers/zmqserver.py
Follow-up to https://github.com/rdeits/meshcat-python/pull/57#issuecomment-622369768
Towards https://github.com/RobotLocomotion/drake/pull/13155
=> Conditionally install ZMQ ioloop for pyzmq < 17

src/meshcat/visualizer.py
=> Fill width of Jupyter cell

src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
=> Implement triangular meshes from vertices and faces

src/meshcat/servers/zmqserver.py
adds arguments --certfile and --keyfile to be passed to HTTPServer.
Updates meshcat SHA
=> add ssl support to zmqserver

examples/box.py, src/meshcat/commands.py, src/meshcat/servers/tree.py, src/meshcat/servers/zmqserver.py, src/meshcat/visualizer.py
note: i did *not* set path.tolower() in set_property, despite the other senders having it.  because i think that is a mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rdeits/meshcat-python/67)
=> plumbs set_property from Visualizer and through the zmqserver

src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
This is just #69 plus a merge with master to fix some trivial conflicts.
=> Updated version of #69

src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
The last step in enabling visualizations like this:
http://people.csail.mit.edu/russt/uploads/planar_iiwa_teleop.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rdeits/meshcat-python/69)
=> Implement set_object OrthographicCamera

.travis.yml, Readme.rst, setup.py, src/meshcat/animation.py, src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/path.py, src/meshcat/servers/zmqserver.py, src/meshcat/tests/test_drawing.py, src/meshcat/tests/test_ports.py, src/meshcat/tests/test_start_server.py, src/meshcat/transformations.py, src/meshcat/visualizer.py
Python2.7 is officially EoL, and it's time to move on :slightly_smiling_face:
=> Drop Python2.7 and require Python3.6 or above

src/meshcat/tests/test_drawing.py
Ref: https://github.com/rdeits/meshcat/pull/97
=> Update meshcat to get three.js 132 and better transparent sphere handling

src/meshcat/tests/test_drawing.py
See: https://github.com/rdeits/meshcat/pull/109
=> Update meshcat to get animation fix

src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/tests/test_drawing.py
=> Add perspective camera bindings (and test)

src/meshcat/commands.py, src/meshcat/geometry.py
This new class was used to fix https://github.com/rdeits/meshcat-python/issues/99
=> Adding perspectiva camera

examples/demo.ipynb, src/meshcat/commands.py, src/meshcat/geometry.py, src/meshcat/servers/zmqserver.py, src/meshcat/visualizer.py
This follows the PR https://github.com/rdeits/meshcat/pull/111. I expose the following new features from that PR:
+ setting the camera target
+ specifying the `get_image()` resolution
Also: 
+ a convenience function for setting camera position (in right-handed coordinates)
=> Features: set captured image resolution, set camera target, set camera position 
